language: python
sudo: false
branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
install:
    - pip install -U pip django
    - pip install -r requirements.txt
script:
    - python manage.py runserver
